export const categories = [
  {
    id: "batteries-electrical",
    name: "Batteries & Electrical",
    description: "Power your vehicle with quality batteries and electrical components",
    image: "/car-battery-electrical.png",
    products: [
      {
        id: "car-batteries",
        name: "Car Batteries",
        description: "Reliable 12V car batteries with high cold cranking amps for dependable starts in any weather.",
        price: "$89.99",
        image: "/car-battery.png",
        inStock: true,
        features: ["12V", "Cold Cranking Amps", "3-Year Warranty"],
      },
      {
        id: "alternators",
        name: "Alternators",
        description: "High-output remanufactured alternators tested for reliable charging performance.",
        price: "$159.99",
        image: "/car-alternator.png",
        inStock: true,
        features: ["High Output", "Remanufactured", "Tested"],
      },
      {
        id: "starters",
        name: "Starters",
        description: "High-torque starter motors for reliable engine starting with direct-fit installation.",
        price: "$129.99",
        image: "/placeholder-1byq7.png",
        inStock: true,
        features: ["High Torque", "Direct Fit", "Warranty"],
      },
      {
        id: "spark-plugs",
        name: "Spark Plugs",
        description: "Premium iridium-tip spark plugs for improved ignition and extended engine life.",
        price: "$12.99",
        image: "/spark-plugs-set.png",
        inStock: true,
        features: ["Iridium Tip", "Long Life", "Set of 4"],
      },
      {
        id: "ignition-coils",
        name: "Ignition Coils",
        description: "OEM-quality ignition coils for reliable spark delivery and smooth engine operation.",
        price: "$45.99",
        image: "/ignition-coil.png",
        inStock: true,
        features: ["OEM Quality", "Direct Replacement", "Tested"],
      },
    ],
  },
  {
    id: "brakes-suspension",
    name: "Brakes & Suspension",
    description: "Stop safely and ride smoothly with our brake and suspension parts",
    image: "/auto-parts.png",
    products: [
      {
        id: "brake-pads",
        name: "Brake Pads",
        description: "Premium ceramic brake pads for quiet, low-dust braking performance.",
        price: "$39.99",
        image: "/placeholder-x685r.png",
        inStock: true,
        features: ["Ceramic", "Low Dust", "Quiet Operation"],
      },
      {
        id: "brake-rotors",
        name: "Brake Rotors / Discs",
        description: "Vented and cross-drilled brake rotors for superior heat dissipation and stopping power.",
        price: "$69.99",
        image: "/brake-rotor-disc.png",
        inStock: true,
        features: ["Vented", "Cross-Drilled", "Balanced"],
      },
      {
        id: "brake-calipers",
        name: "Brake Calipers",
        description: "Remanufactured brake calipers tested for reliable braking with core exchange available.",
        price: "$89.99",
        image: "/brake-caliper.png",
        inStock: true,
        features: ["Remanufactured", "Tested", "Core Exchange"],
      },
      {
        id: "shock-absorbers",
        name: "Shock Absorbers / Struts",
        description: "Gas-charged shock absorbers and struts for improved ride comfort and handling.",
        price: "$79.99",
        image: "/shock-absorber-strut.png",
        inStock: true,
        features: ["Gas Charged", "Direct Fit", "Smooth Ride"],
      },
      {
        id: "control-arms",
        name: "Control Arms",
        description: "Complete control arm assemblies with ball joints and bushings for precise steering control.",
        price: "$95.99",
        image: "/control-arm-suspension.png",
        inStock: true,
        features: ["Ball Joint Included", "Bushings", "Complete Assembly"],
      },
    ],
  },
  {
    id: "engine-cooling",
    name: "Engine & Cooling",
    description: "Keep your engine running cool and clean with our filters and cooling parts",
    image: "/engine-air-filter-radiator.png",
    products: [
      {
        id: "air-filters",
        name: "Air Filters",
        description: "High-flow washable air filters for improved engine performance and longevity.",
        price: "$19.99",
        image: "/engine-air-filter.png",
        inStock: true,
        features: ["High Flow", "Washable", "Long Life"],
      },
      {
        id: "oil-filters",
        name: "Oil Filters",
        description: "Premium spin-on oil filters with anti-drainback valve for superior engine protection.",
        price: "$14.99",
        image: "/oil-filter.png",
        inStock: true,
        features: ["Spin-On", "Premium Media", "Anti-Drainback"],
      },
      {
        id: "fuel-filters",
        name: "Fuel Filters",
        description: "High-efficiency in-line fuel filters for clean fuel delivery and optimal engine performance.",
        price: "$24.99",
        image: "/fuel-filter.png",
        inStock: true,
        features: ["In-Line", "High Efficiency", "Easy Install"],
      },
      {
        id: "radiators",
        name: "Radiators",
        description: "Aluminum core radiators with direct-fit design for optimal engine cooling performance.",
        price: "$189.99",
        image: "/car-radiator.png",
        inStock: true,
        features: ["Aluminum Core", "Direct Fit", "Pressure Tested"],
      },
      {
        id: "water-pumps",
        name: "Water Pumps",
        description: "OEM-specification water pumps with new impellers for reliable coolant circulation.",
        price: "$79.99",
        image: "/water-pump-industrial.png",
        inStock: true,
        features: ["New Impeller", "Gasket Included", "OEM Spec"],
      },
      {
        id: "belts",
        name: "Belts (Timing, Serpentine)",
        description: "EPDM rubber belts with stretch-fit design for quiet, reliable operation.",
        price: "$29.99",
        image: "/placeholder-ze5xx.png",
        inStock: true,
        features: ["EPDM Rubber", "Stretch Fit", "Quiet Operation"],
      },
      {
        id: "hoses",
        name: "Hoses",
        description: "Molded-fit radiator hoses with heat-resistant construction and included clamps.",
        price: "$34.99",
        image: "/radiator-hose.png",
        inStock: true,
        features: ["Molded Fit", "Heat Resistant", "Clamps Included"],
      },
    ],
  },
  {
    id: "transmission-drivetrain",
    name: "Transmission & Drivetrain",
    description: "Power transfer components for smooth shifting and driving",
    image: "/auto-parts.png",
    products: [
      {
        id: "clutch-kits",
        name: "Clutch Kits",
        description: "Complete clutch kits with pressure plate and release bearing for smooth shifting.",
        price: "$199.99",
        image: "/clutch-kit.png",
        inStock: true,
        features: ["Complete Kit", "Pressure Plate", "Release Bearing"],
      },
      {
        id: "cv-axles",
        name: "CV Axles",
        description: "Balanced CV axles with new joints and boots for smooth power transfer.",
        price: "$119.99",
        image: "/cv-axle.png",
        inStock: true,
        features: ["New CV Joint", "Boot Included", "Balanced"],
      },
      {
        id: "u-joints",
        name: "U-Joints",
        description: "Heavy-duty greasable universal joints with precision fit for reliable operation.",
        price: "$39.99",
        image: "/universal-joint.png",
        inStock: true,
        features: ["Greasable", "Heavy Duty", "Precision Fit"],
      },
      {
        id: "wheel-bearings",
        name: "Wheel Bearings",
        description: "Pre-greased wheel bearing hub assemblies with ABS sensors for smooth wheel rotation.",
        price: "$59.99",
        image: "/placeholder.svg?height=200&width=200",
        inStock: true,
        features: ["Hub Assembly", "ABS Sensor", "Pre-Greased"],
      },
    ],
  },
  {
    id: "fluids-maintenance",
    name: "Fluids & Maintenance",
    description: "Essential fluids to keep your vehicle running smoothly",
    image: "/placeholder.svg?height=200&width=300",
    products: [
      {
        id: "motor-oil",
        name: "Motor Oil",
        description: "Full synthetic 5W-30 motor oil in convenient 5-quart jugs for optimal engine protection.",
        price: "$24.99",
        image: "/placeholder.svg?height=200&width=200",
        inStock: true,
        features: ["5W-30", "Full Synthetic", "5 Quart Jug"],
      },
      {
        id: "transmission-fluid",
        name: "Transmission Fluid",
        description: "Multi-vehicle automatic transmission fluid for smooth shifting and transmission protection.",
        price: "$19.99",
        image: "/placeholder.svg?height=200&width=200",
        inStock: true,
        features: ["ATF", "Multi-Vehicle", "1 Quart"],
      },
      {
        id: "coolant",
        name: "Coolant / Antifreeze",
        description: "Extended-life 50/50 coolant mix for optimal engine temperature control and protection.",
        price: "$16.99",
        image: "/placeholder.svg?height=200&width=200",
        inStock: true,
        features: ["50/50 Mix", "Extended Life", "1 Gallon"],
      },
      {
        id: "brake-fluid",
        name: "Brake Fluid",
        description: "DOT 3 brake fluid with high boiling point for reliable braking performance.",
        price: "$12.99",
        image: "/placeholder.svg?height=200&width=200",
        inStock: true,
        features: ["DOT 3", "High Boiling Point", "12 oz"],
      },
      {
        id: "washer-fluid",
        name: "Windshield Washer Fluid",
        description: "All-season windshield washer fluid with bug remover for clear visibility.",
        price: "$3.99",
        image: "/placeholder.svg?height=200&width=200",
        inStock: true,
        features: ["All Season", "Bug Remover", "1 Gallon"],
      },
    ],
  },
  {
    id: "lighting-accessories",
    name: "Lighting & Accessories",
    description: "Illuminate your way with quality lighting and essential accessories",
    image: "/placeholder.svg?height=200&width=300",
    products: [
      {
        id: "headlights",
        name: "Headlights",
        description: "DOT-approved halogen headlights for direct replacement and improved visibility.",
        price: "$89.99",
        image: "/placeholder.svg?height=200&width=200",
        inStock: true,
        features: ["Halogen", "DOT Approved", "Direct Replacement"],
      },
      {
        id: "tail-lights",
        name: "Tail Lights",
        description: "LED tail lights with red lenses for enhanced visibility and easy installation.",
        price: "$69.99",
        image: "/placeholder.svg?height=200&width=200",
        inStock: true,
        features: ["LED", "Red Lens", "Easy Install"],
      },
      {
        id: "fog-lights",
        name: "Fog Lights",
        description: "Clear lens fog lights with H11 bulbs and complete wiring for improved visibility.",
        price: "$49.99",
        image: "/placeholder.svg?height=200&width=200",
        inStock: true,
        features: ["Clear Lens", "H11 Bulb", "Wiring Included"],
      },
      {
        id: "turn-signals",
        name: "Turn Signal Bulbs",
        description: "Long-life amber turn signal bulbs for reliable signaling and safety.",
        price: "$8.99",
        image: "/placeholder.svg?height=200&width=200",
        inStock: true,
        features: ["Amber", "Long Life", "Pack of 2"],
      },
      {
        id: "wiper-blades",
        name: "Wiper Blades",
        description: "All-weather beam-style wiper blades for clear visibility in any conditions.",
        price: "$19.99",
        image: "/placeholder.svg?height=200&width=200",
        inStock: true,
        features: ["All Weather", "Beam Style", "Easy Install"],
      },
    ],
  },
  {
    id: "interior-exterior",
    name: "Interior & Exterior Essentials",
    description: "Complete your vehicle with interior comfort and exterior style",
    image: "/placeholder.svg?height=200&width=300",
    products: [
      {
        id: "floor-mats",
        name: "Floor Mats",
        description: "Custom-fit all-weather floor mats for complete interior protection in all conditions.",
        price: "$39.99",
        image: "/placeholder.svg?height=200&width=200",
        inStock: true,
        features: ["All Weather", "Custom Fit", "Set of 4"],
      },
      {
        id: "mirrors",
        name: "Mirrors (side & rearview)",
        description: "Power-adjustable heated mirrors with turn signals for enhanced visibility and convenience.",
        price: "$59.99",
        image: "/placeholder.svg?height=200&width=200",
        inStock: true,
        features: ["Power Adjust", "Heated", "Turn Signal"],
      },
      {
        id: "door-handles",
        name: "Door Handles",
        description: "Chrome-finish exterior door handles with direct-fit design for easy replacement.",
        price: "$29.99",
        image: "/placeholder.svg?height=200&width=200",
        inStock: true,
        features: ["Exterior", "Chrome Finish", "Direct Fit"],
      },
      {
        id: "hubcaps",
        name: "Hubcaps / Wheel Covers",
        description: "16-inch chrome hubcaps for enhanced wheel appearance and protection.",
        price: "$79.99",
        image: "/placeholder.svg?height=200&width=200",
        inStock: true,
        features: ["16 Inch", "Chrome", "Set of 4"],
      },
    ],
  },
]

export const getAllProducts = () => {
  return categories.flatMap((category) =>
    category.products.map((product) => ({
      ...product,
      categoryId: category.id,
      categoryName: category.name,
    })),
  )
}

export const getProductsByCategory = (categoryId: string) => {
  const category = categories.find((cat) => cat.id === categoryId)
  return category ? category.products : []
}

export const getProductById = (productId: string) => {
  const allProducts = getAllProducts()
  return allProducts.find((product) => product.id === productId)
}
